from netcat import *
sender = input('What is the address you are sending the email from?\n')
reciever = input('What is the address you want to send to?\n')
subject = input('What is the subject for the email?\n')
filename = input('What is the filename that contains the contents of the email?\n')
nc = Netcat()
nc.connect("mail-relay.IU.Edu", 25)
#raw_data = nc.read(1024)
#print(raw_data.decode('utf-8'))
nc.write("HELO test\n")
nc.write("MAIL FROM:"+sender+"\n")
#raw_data = nc.read(1024)
#print(raw_data.decode('utf-8'))
nc.write("RCPT TO:"+reciever+"\n")
#raw_data = nc.read(1024)
#print(raw_data.decode('utf-8'))
nc.write("DATA\n")
#raw_data = nc.read(1024)
#print(raw_data.decode('utf-8'))
nc.write("Subject:"+subject+"\n")
f = open(filename, "r")
nc.write(f.read() + "\n")
nc.write(".\n")
f.close()
nc.close()
